# Generated by Django 4.2.17 on 2024-12-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10, unique=True, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('role', models.CharField(choices=[('DOC', '医生'), ('NUR', '护士'), ('ADM', '管理员')], default='NUR', max_length=3, verbose_name='角色')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='科室')),
            ],
            options={
                'verbose_name': '医护人员',
                'verbose_name_plural': '医护人员',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='证件号码')),
                ('name_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('pinyin_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', '未知')], default='Unknown', max_length=10, verbose_name='血型')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系人电话')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='过敏史')),
            ],
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('status', models.CharField(choices=[('WAITING', '等候中'), ('IN_PROGRESS', '就诊中'), ('COMPLETED', '已完成'), ('LEFT', '离开')], default='WAITING', max_length=15, verbose_name='状态')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='发病时间')),
                ('arrival_method', models.CharField(choices=[('WALK', '步行'), ('WHEELCHAIR', '轮椅'), ('STRETCHER', '担架'), ('AMB_120', '120'), ('SELF', '自行来院')], default='WALK', max_length=10, verbose_name='来院方式')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='主诉')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='既往史')),
                ('priority_level', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=4, verbose_name='分诊等级')),
                ('area', models.CharField(choices=[('RED', '红区'), ('YELLOW', '黄区'), ('GREEN', '绿区')], default='GREEN', max_length=6, verbose_name='分区')),
                ('treatment_area', models.CharField(blank=True, choices=[('RESUS', '抢救区'), ('OBS', '留观区'), ('TREAT', '诊疗区')], max_length=5, null=True, verbose_name='就诊区域')),
                ('transfer_status', models.CharField(choices=[('NONE', '无需转诊'), ('UP', '向上级医院转诊'), ('DOWN', '向下级医院转诊')], default='NONE', max_length=4, verbose_name='转诊安排')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='分诊科室')),
                ('preliminary_diagnosis', models.TextField(blank=True, null=True, verbose_name='初步诊断')),
                ('followup_type', models.CharField(choices=[('NONE', '无需复诊'), ('ONLINE', '线上复诊'), ('OFFLINE', '线下复诊')], default='NONE', max_length=10, verbose_name='复诊安排')),
                ('followup_notes', models.TextField(blank=True, null=True, verbose_name='复诊备注')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.medicalstaff', verbose_name='分诊护士')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='呼吸频率')),
                ('avpu_status', models.CharField(choices=[('A', 'Alert'), ('V', 'Voice'), ('P', 'Pain'), ('U', 'Unresponsive')], default='A', max_length=1, verbose_name='AVPU评分')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='血氧饱和度')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='血糖')),
                ('pain_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='疼痛评分')),
                ('trauma_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='创伤评分')),
                ('measurement_time', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('mews_score', models.IntegerField(default=0, verbose_name='MEWS评分')),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triage.triagerecord')),
            ],
        ),
    ]
