# Generated by Django 4.2.17 on 2024-12-28 23:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='医院名称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '医院',
                'verbose_name_plural': '医院',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('staff_id', models.CharField(max_length=10, unique=True, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('role', models.CharField(choices=[('DOC', '医生'), ('NUR', '护士'), ('ADM', '管理员')], default='NUR', max_length=3, verbose_name='角色')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='科室')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='所属医院')),
            ],
            options={
                'verbose_name': '医护人员',
                'verbose_name_plural': '医护人员',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_system', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('id_his', models.CharField(blank=True, max_length=50, null=True, verbose_name='HIS系统ID')),
                ('name_patient', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('pinyin_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=1, null=True, verbose_name='性别')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('id_type', models.CharField(blank=True, choices=[('ID', '居民身份证'), ('HUKOU', '居民户口本'), ('HMT', '港澳台居民来往内地通行证'), ('PERMANENT', '外国人永久居留证'), ('PASSPORT', '护照'), ('MILITARY', '军官证')], default='ID', max_length=10, null=True, verbose_name='证件类型')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='证件号码')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍')),
                ('ethinicity', models.CharField(blank=True, max_length=50, null=True, verbose_name='民族')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='职业')),
                ('id_medical_insurance', models.CharField(blank=True, max_length=16, null=True, verbose_name='医保卡号')),
                ('id_social_insurance', models.CharField(blank=True, max_length=9, null=True, verbose_name='社保卡号')),
                ('id_hospital_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='诊疗卡号')),
                ('insurance_type', models.CharField(blank=True, choices=[('SELF', '自费'), ('PUBLIC', '公费'), ('MEDICAL', '医保'), ('COMMERCIAL', '商保'), ('EMPLOYEE', '本院职工'), ('EMPLOYEE_FAMILY', '职工家属'), ('OTHER_REGION', '异地医保'), ('NEW_RURAL', '新农合'), ('URBAN_RURAL', '城乡医保'), ('FIVE_SPECIAL', '五保特困'), ('LOW_INCOME', '低保'), ('MILITARY', '军烈'), ('EARTHQUAKE_512', '512地震'), ('MINOR_INJURY', '轻轨工伤'), ('RAILWAY', '铁路医保'), ('ROAD_FUND', '道路基金'), ('DISABILITY', '复员伤残'), ('DISABLED', '残疾'), ('SPONSOR', '担保'), ('HOMELESS', '无主病人'), ('LEAVE', '离休'), ('WORK_INJURY', '工伤'), ('CAR_INJURY', '车伤'), ('MATERNITY', '生育'), ('SPECIAL', '特约')], default='SELF', max_length=20, null=True, verbose_name='费别')),
                ('patient_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('patient_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', '未知')], default='Unknown', max_length=10, null=True, verbose_name='血型')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系人电话')),
                ('emergency_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人关系')),
                ('patient_type', models.CharField(blank=True, choices=[('THREE_NO', '三无人员'), ('LOW_INCOME', '低保户'), ('SPECIAL_POVERTY', '特困户'), ('CARD_POVERTY', '建卡贫困户'), ('FIVE_GUARANTEE', '五保户'), ('MILITARY_8023', '8023部队'), ('ACTIVE_MILITARY', '现役军人'), ('RETIRED_MILITARY', '退伍军人'), ('ORPHANED', '失独人员')], default='THREE_NO', max_length=20, null=True, verbose_name='身份标识')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='过敏史')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='所属医院')),
            ],
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间')),
                ('illness_time', models.DateTimeField(blank=True, null=True, verbose_name='发病时间')),
                ('arrival_method', models.CharField(blank=True, choices=[('WALK', '步行'), ('CARRIED', '抱送'), ('STRETCHER', '扶入'), ('WHEELCHAIR', '轮椅'), ('FLATBED', '平车'), ('LOCAL_120', '本院120'), ('EXTERNAL_120', '外院120'), ('POLICE_110', '110'), ('DOA', '院外死亡')], default='WALK', max_length=20, null=True, verbose_name='来院方式')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='主诉')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='既往史')),
                ('speed_channel', models.CharField(blank=True, choices=[('CHEST_PAIN', '胸痛'), ('STROKE', '卒中'), ('TRAUMA', '创伤'), ('PEDIATRIC_EMERGENCY', '危重儿童和新生儿'), ('HIGH_RISK_PREGNANCY', '高危孕产妇'), ('POISONING', '中毒'), ('COVID', '新冠肺炎'), ('CARDIAC_ARREST', '心衰'), ('BRAIN_INJURY', '重型颅脑损伤'), ('RESPIRATORY_FAILURE', '呼吸衰竭'), ('VACCINE_REACTION', '新冠疫苗不良反应'), ('CARDIOVASCULAR', '心血管'), ('CARDIOPULMONARY_ARREST', '心跳呼吸骤停'), ('SHOCK', '休克'), ('OTHER', '其他')], max_length=30, null=True, verbose_name='绿色通道')),
                ('specialty_type', models.CharField(blank=True, choices=[('CHEST_PAIN', '胸痛'), ('POST_STROKE', '卒中过'), ('TRAUMA', '创伤'), ('HIGH_RISK_PREGNANCY', '高危孕产妇'), ('PEDIATRIC_EMERGENCY', '危急儿童和新生儿')], max_length=30, null=True, verbose_name='专科中心')),
                ('other_inquiry', models.CharField(blank=True, choices=[('ADMISSION_CERT', '开住院证'), ('PRESCRIPTION', '开药'), ('MEDICAL_ORDER', '开单'), ('NUCLEIC_TEST', '核酸检测')], max_length=20, null=True, verbose_name='非急诊类')),
                ('surgery_type', models.CharField(blank=True, choices=[('DEBRIDEMENT', '清创'), ('SUTURE', '缝合'), ('REMOVAL', '拆线'), ('MEDICATION_CHANGE', '换药')], max_length=20, null=True, verbose_name='手术')),
                ('ifmass_injury', models.CharField(blank=True, choices=[('YES', '是'), ('NO', '否')], max_length=5, null=True, verbose_name='是否群伤')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to=settings.AUTH_USER_MODEL, verbose_name='所属医院')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to='triage.medicalstaff', verbose_name='分诊护士')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to='triage.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='呼吸频率')),
                ('avpu_status', models.CharField(blank=True, choices=[('A', '清醒'), ('V', '对声音有反应'), ('P', '对疼痛有反应'), ('U', '无反应')], default='A', max_length=1, null=True, verbose_name='AVPU评分')),
                ('blood_potassium', models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=4, null=True, verbose_name='血钾')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='血氧饱和度')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='血糖')),
                ('conscious_status', models.CharField(blank=True, choices=[('CLEAR', '清醒'), ('DROWSY', '嗜睡'), ('LETHARGY', '昏睡'), ('SEMI_COMA', '半昏迷'), ('COMA', '昏迷')], max_length=20, null=True, verbose_name='意识')),
                ('pain_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='疼痛评分')),
                ('trauma_score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='创伤评分')),
                ('injury_position', models.CharField(blank=True, choices=[('LIMBS_SKIN', '四肢/皮肤'), ('BACK', '背部'), ('CHEST', '胸部'), ('ABDOMEN', '腹部'), ('HEAD_NECK', '头颈部')], max_length=20, null=True, verbose_name='损伤部位')),
                ('injury_type', models.CharField(blank=True, choices=[('LACERATION', '裂伤/挫伤'), ('STAB', '刺伤'), ('BLUNT', '钝性伤'), ('GUNSHOT', '弹道伤')], max_length=20, null=True, verbose_name='损伤类型')),
                ('eyeopen_status', models.CharField(blank=True, choices=[('NORMAL', '正常睁眼'), ('CALL', '呼唤睁眼'), ('PAIN', '刺痛睁眼'), ('NONE', '无反应')], max_length=20, null=True, verbose_name='睁眼反应')),
                ('response_status', models.CharField(blank=True, choices=[('CORRECT', '回答正确'), ('INCORRECT', '回答错误'), ('INCOHERENT', '语无伦次'), ('SOUNDS_ONLY', '只能发声'), ('NONE', '不能发声')], max_length=20, null=True, verbose_name='语言反应')),
                ('move_status', models.CharField(blank=True, choices=[('OBEY', '遵嘱运动'), ('LOCALIZE_PAIN', '刺痛定位'), ('WITHDRAW_PAIN', '躲避刺痛'), ('FLEXION_PAIN', '刺痛肢屈'), ('EXTENSION_PAIN', '刺痛肢伸'), ('NONE', '无反应')], max_length=20, null=True, verbose_name='运动反应')),
                ('gcs_score', models.IntegerField(blank=True, null=True, verbose_name='GCS评分')),
                ('rems_score', models.IntegerField(blank=True, null=True, verbose_name='REMS评分')),
                ('measurement_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='测量时间')),
                ('mews_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='MEWS评分')),
                ('triage_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitalsigns', to='triage.triagerecord')),
            ],
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_status', models.CharField(blank=True, choices=[('WAITING', '未分诊'), ('IN_PROGRESS', '已分诊'), ('COMPLETED', '已就医'), ('LEFT', '离开')], default='WAITING', max_length=15, null=True, verbose_name='状态')),
                ('priority_level', models.IntegerField(blank=True, choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=4, null=True, verbose_name='分诊等级')),
                ('triage_area', models.CharField(blank=True, choices=[('RED', '红区'), ('YELLOW', '黄区'), ('GREEN', '绿区')], default='GREEN', max_length=6, null=True, verbose_name='分区')),
                ('treatment_area', models.CharField(blank=True, choices=[('RESUS', '抢救区'), ('OBS', '留观区'), ('TREAT', '诊疗区')], max_length=5, null=True, verbose_name='就诊区域')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='分诊科室')),
                ('patient_nextstep', models.TextField(blank=True, null=True, verbose_name='患者去向')),
                ('transfer_status', models.CharField(blank=True, choices=[('NONE', '无需转诊'), ('HIGHER', '向上级医院转诊'), ('LOWER', '向下级医院转诊')], max_length=20, null=True, verbose_name='转诊安排')),
                ('transfer_hospital', models.CharField(blank=True, max_length=100, null=True, verbose_name='转诊医院')),
                ('transfer_reason', models.TextField(blank=True, null=True, verbose_name='转诊原因')),
                ('triage_group', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='组别')),
                ('preliminary_diagnosis', models.TextField(blank=True, null=True, verbose_name='初步诊断')),
                ('followup_type', models.CharField(blank=True, choices=[('NONE', '无需复诊'), ('ONLINE', '线上复诊'), ('OFFLINE', '线下复诊')], default='NONE', max_length=10, null=True, verbose_name='复诊安排')),
                ('followup_info', models.TextField(blank=True, null=True, verbose_name='复诊备注')),
                ('triage_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='triage.triagerecord')),
            ],
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='triage.hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
