# Generated by Django 4.2.17 on 2024-12-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_type',
            field=models.CharField(choices=[('ID', '居民身份证'), ('PASSPORT', '护照'), ('HK_MO', '港澳通行证'), ('TW', '台湾通行证'), ('FOREIGN', '外国人永久居留证'), ('OTHER', '其他证件')], default='ID', max_length=10, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='证件号码'),
        ),
    ]
