# Generated by Django 4.2.17 on 2024-12-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagerecord',
            name='specialty_type',
            field=models.CharField(blank=True, choices=[('CHEST_PAIN', '胸痛'), ('POST_STROKE', '卒中'), ('TRAUMA', '创伤'), ('HIGH_RISK_PREGNANCY', '高危孕产妇'), ('PEDIATRIC_EMERGENCY', '危急儿童和新生儿')], max_length=30, null=True, verbose_name='专科中心'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='department',
            field=models.CharField(blank=True, choices=[('EMERGENCY_MEDICINE', '急诊内科'), ('EMERGENCY_SURGERY', '急诊外科'), ('ORTHOPEDICS', '骨科'), ('NEUROLOGY', '神经内科'), ('NEUROSURGERY', '神经外科'), ('PEDIATRICS', '儿科'), ('OBSTETRICS', '妇产科'), ('OPHTHALMOLOGY', '眼科'), ('ENT', '耳鼻喉科'), ('STOMATOLOGY', '口腔科'), ('DERMATOLOGY', '皮肤科'), ('ANIMAL_INJURY', '动物致伤'), ('GASTROENTEROLOGY', '消化内科'), ('UROLOGY', '泌尿外科'), ('PLASTIC_SURGERY', '整形外科'), ('THORACIC', '胸外科'), ('NEPHROLOGY', '肾内科'), ('CARDIOLOGY', '心内科'), ('BURN', '烧伤科'), ('TOXICOLOGY', '中毒中心'), ('FEVER_CLINIC', '发热门诊'), ('EICU', 'EICU')], max_length=50, null=True, verbose_name='分诊科室'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='patient_nextstep',
            field=models.CharField(blank=True, choices=[('DEATH', '死亡'), ('LEAVE_AMA', '自行离院'), ('DISCHARGE', '正常出院'), ('TRANSFER_WARD', '转住院'), ('TRANSFER_DEPT', '转科')], max_length=20, null=True, verbose_name='患者去向'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='triage_status',
            field=models.CharField(blank=True, choices=[('WAITING', '未分诊'), ('IN_PROGRESS', '已分诊'), ('COMPLETED', '已就医'), ('LEFT', '已离开')], default='WAITING', max_length=15, null=True, verbose_name='状态'),
        ),
    ]
