# Generated by Django 4.2.17 on 2024-12-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_patient_id_type_alter_patient_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='证件号码'),
        ),
    ]
