# Generated by Django 4.2.17 on 2024-12-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_triagerecord_specialty_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='chief_symptom',
            field=models.CharField(blank=True, choices=[('BLEEDING', '加压止血无法控制/急性出血'), ('CHEST_PAIN', '胸痛胸闷，呼吸困难'), ('PREGNANCY_PAIN', '孕妇剧烈腹痛'), ('HIGH_FEVER', '持续高烧>38.5摄氏度'), ('CONSCIOUSNESS', '突发意识改变（嗜睡，定向障碍，昏厥）'), ('HEAD_INJURY', '头/眼受伤')], max_length=50, null=True, verbose_name='快捷分诊'),
        ),
    ]
