# Generated by Django 4.2.17 on 2024-12-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_patient_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagerecord',
            name='area',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='followup_notes',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='followup_type',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='preliminary_diagnosis',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='transfer_status',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='treatment_area',
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '等候中'), ('IN_PROGRESS', '就诊中'), ('COMPLETED', '已完成'), ('LEFT', '离开')], default='WAITING', max_length=15, verbose_name='状态')),
                ('priority_level', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=4, verbose_name='分诊等级')),
                ('area', models.CharField(choices=[('RED', '红区'), ('YELLOW', '黄区'), ('GREEN', '绵区')], default='GREEN', max_length=6, verbose_name='分区')),
                ('treatment_area', models.CharField(blank=True, choices=[('RESUS', '抢救区'), ('OBS', '留观区'), ('TREAT', '诊疗区')], max_length=5, null=True, verbose_name='就诊区域')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='分诊科室')),
                ('preliminary_diagnosis', models.TextField(blank=True, null=True, verbose_name='初步诊断')),
                ('transfer_status', models.CharField(choices=[('NONE', '无需转诊'), ('UP', '向上级医院转诊'), ('DOWN', '向下级医院转诊')], default='NONE', max_length=4, verbose_name='转诊安排')),
                ('followup_type', models.CharField(choices=[('NONE', '无需复诊'), ('ONLINE', '线上复诊'), ('OFFLINE', '线下复诊')], default='NONE', max_length=10, verbose_name='复诊安排')),
                ('followup_notes', models.TextField(blank=True, null=True, verbose_name='复诊备注')),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='triage.triagerecord')),
            ],
        ),
    ]
