# Generated by Django 4.2.17 on 2024-12-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_remove_triagerecord_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageresult',
            name='area',
            field=models.CharField(choices=[('RED', '红区'), ('YELLOW', '黄区'), ('GREEN', '绿区')], default='GREEN', max_length=6, verbose_name='分区'),
        ),
    ]
