# Generated by Django 4.2.17 on 2024-12-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_alter_triageresult_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pinyin_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', '未知')], default='Unknown', max_length=10, null=True, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ID', '居民身份证'), ('PASSPORT', '护照'), ('HK_MO', '港澳通行证'), ('TW', '台湾通行证'), ('FOREIGN', '外国人永久居留证'), ('OTHER', '其他证件')], default='ID', max_length=10, null=True, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='arrival_method',
            field=models.CharField(blank=True, choices=[('WALK', '步行'), ('WHEELCHAIR', '轮椅'), ('STRETCHER', '担架'), ('AMB_120', '120'), ('SELF', '自行来院')], default='WALK', max_length=10, null=True, verbose_name='来院方式'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.medicalstaff', verbose_name='分诊护士'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.patient'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='area',
            field=models.CharField(blank=True, choices=[('RED', '红区'), ('YELLOW', '黄区'), ('GREEN', '绿区')], default='GREEN', max_length=6, null=True, verbose_name='分区'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='followup_type',
            field=models.CharField(blank=True, choices=[('NONE', '无需复诊'), ('ONLINE', '线上复诊'), ('OFFLINE', '线下复诊')], default='NONE', max_length=10, null=True, verbose_name='复诊安排'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='priority_level',
            field=models.IntegerField(blank=True, choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=4, null=True, verbose_name='分诊等级'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='status',
            field=models.CharField(blank=True, choices=[('WAITING', '等候中'), ('IN_PROGRESS', '就诊中'), ('COMPLETED', '已完成'), ('LEFT', '离开')], default='WAITING', max_length=15, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('NONE', '无需转诊'), ('UP', '向上级医院转诊'), ('DOWN', '向下级医院转诊')], default='NONE', max_length=4, null=True, verbose_name='转诊安排'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='triage_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='triage.triagerecord'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='avpu_status',
            field=models.CharField(blank=True, choices=[('A', 'Alert'), ('V', 'Voice'), ('P', 'Pain'), ('U', 'Unresponsive')], default='A', max_length=1, null=True, verbose_name='AVPU评分'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='measurement_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='测量时间'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='mews_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='MEWS评分'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='triage_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triagerecord'),
        ),
    ]
