# Generated by Django 4.2.17 on 2024-12-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_remove_patient_pinyin_name_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to='triage.patient'),
        ),
    ]
