# Generated by Django 4.2.17 on 2024-12-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_alter_vitalsigns_injury_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('DOC', '医生'), ('NUR', '护士'), ('ADM', '管理员')], default='NUR', max_length=3, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='工号'),
        ),
    ]
