# Generated by Django 4.2.17 on 2024-12-24 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_alter_triagerecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagerecord',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间'),
        ),
    ]
