# Generated by Django 4.2.17 on 2025-01-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_alter_vitalsigns_injury_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='injury_position',
            field=models.TextField(blank=True, null=True, verbose_name='损伤部位'),
        ),
    ]
