# Generated by Django 4.2.17 on 2025-01-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_alter_vitalsigns_injury_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='injury_position',
            field=models.CharField(blank=True, choices=[('LIMBS_SKIN', '四肢/皮肤'), ('BACK', '背部'), ('CHEST', '胸部'), ('ABDOMEN', '腹部'), ('HEAD_NECK', '头颈部'), ('BUTTOCKS', '臀部')], max_length=255, null=True, verbose_name='损伤部位'),
        ),
    ]
