# Generated by Django 4.2.17 on 2025-01-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0010_alter_patientuser_id'),
        ('triage', '0011_patient_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patient_portal.patientuser'),
        ),
    ]
