# Generated by Django 4.2.17 on 2025-01-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0014_alter_patient_id_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='revised_trauma',
            field=models.IntegerField(blank=True, null=True, verbose_name='修订创伤评分（前端自动生成）'),
        ),
    ]
