# Generated by Django 4.2.17 on 2025-01-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0015_vitalsigns_revised_trauma'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_time', models.DateTimeField(blank=True, null=True, verbose_name='事件时间')),
                ('mass_type', models.CharField(blank=True, choices=[('FIGHT', '打架'), ('TRAFFIC', '车祸'), ('FLOOD', '洪水'), ('FIRE', '火灾'), ('EARTHQUAKE', '地震'), ('MUDSLIDE', '泥石流'), ('TYPHOON', '台风'), ('EXPLOSION', '爆炸'), ('PUBLIC_HEALTH', '公共卫生'), ('FOOD_POISON', '食物中毒'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='事件类型')),
                ('mass_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='事件名称')),
                ('mass_number', models.IntegerField(blank=True, null=True, verbose_name='群伤人数')),
                ('mass_notes', models.TextField(blank=True, null=True, verbose_name='补充说明')),
            ],
            options={
                'verbose_name': '群伤',
                'verbose_name_plural': '群伤',
                'ordering': ['-mass_time'],
            },
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='mass_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to='triage.massinjury', verbose_name='群伤事件'),
        ),
    ]
