# Generated by Django 4.2.17 on 2025-01-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0016_massinjury_triagerecord_mass_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='massinjury',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mass_injuries', to=settings.AUTH_USER_MODEL, verbose_name='所属医院'),
        ),
    ]
