# Generated by Django 4.2.17 on 2025-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0018_alter_triagerecord_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagehistoryinfo',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='triagehistoryinfo',
            name='assigned_nurse',
        ),
    ]
