# Generated by Django 4.2.17 on 2025-01-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0019_remove_triagehistoryinfo_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageresult',
            name='triage_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triage.triagerecord'),
        ),
    ]
