# Generated by Django 4.2.17 on 2025-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0020_alter_triageresult_triage_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageresult',
            name='treatment_area',
            field=models.CharField(blank=True, choices=[('RESUS', '抢救区'), ('OBS', '留观区'), ('TREAT', '诊疗区')], max_length=50, null=True, verbose_name='就诊区域'),
        ),
    ]
