# Generated by Django 4.2.17 on 2025-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0022_alter_massinjury_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaluser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
