# Generated by Django 4.2.17 on 2025-01-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0024_alter_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
