# Generated by Django 4.2.17 on 2025-02-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0026_alter_vitalsigns_injury_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='区/县'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.CharField(blank=True, choices=[('3A', '三甲医院'), ('3', '三级医院'), ('2', '二级医院'), ('1', '一级医院'), ('U', '未定级医院')], max_length=2, null=True, verbose_name='医院级别'),
        ),
    ]
