# Generated by Django 4.2.17 on 2025-02-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0027_hospital_city_hospital_district_hospital_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='district',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='level',
        ),
    ]
