# Generated by Django 4.2.17 on 2025-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0028_remove_hospital_city_remove_hospital_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.CharField(blank=True, choices=[('A', '三甲医院'), ('B', '三级医院'), ('C', '二级医院'), ('D', '一级医院'), ('E', '未分级')], max_length=10, null=True, verbose_name='医院等级'),
        ),
    ]
