# Generated by Django 4.2.17 on 2025-02-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0029_hospital_city_hospital_district_hospital_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
