# Generated by Django 4.2.17 on 2025-02-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0030_alter_medicalstaff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('request_type', models.CharField(blank=True, choices=[('SOFTWARE', '软件功能'), ('INFO', '医院信息更新'), ('BILLING', '咨询费用'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='问题类型')),
                ('request_content', models.TextField(blank=True, null=True, verbose_name='问题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='提交时间')),
                ('hospital_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='医院用户')),
            ],
            options={
                'verbose_name': '医院反馈feedback',
                'verbose_name_plural': '医院反馈feedback',
            },
        ),
    ]
