# Generated by Django 4.2.17 on 2024-12-30 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0004_alter_triagerecord_chief_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTriageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已通过')], default='PENDING', max_length=20, verbose_name='状态')),
                ('name_patient', models.CharField(blank=True, max_length=100, null=True, verbose_name='患者姓名')),
                ('gender', models.CharField(blank=True, choices=[('F', '女'), ('M', '男')], max_length=10, null=True, verbose_name='性别')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_type', models.CharField(blank=True, choices=[('ID_CARD', '居民身份证'), ('HUKOU', '居民户口本'), ('HK_MC_TW', '港澳台居民来往内地通行证'), ('FOREIGNER', '外国人永久居留证'), ('PASSPORT', '护照'), ('MILITARY', '军官证')], max_length=20, null=True, verbose_name='证件类型')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='证件号码')),
                ('id_medical_insurance', models.CharField(blank=True, max_length=50, null=True, verbose_name='医保卡号')),
                ('id_hospital_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='诊疗卡号')),
                ('patient_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='患者电话')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='主诉')),
                ('chief_symptom', models.CharField(blank=True, choices=[('BLEEDING', '加压止血无法控制/急性出血'), ('CHEST_PAIN', '胸痛胸闷，呼吸困难'), ('PREGNANCY_PAIN', '孕妇剧烈腹痛'), ('HIGH_FEVER', '持续高烧>38.5摄氏度'), ('CONSCIOUSNESS', '突发意识改变（嗜睡，定向障碍，昏厥）'), ('HEAD_INJURY', '头/眼受伤')], max_length=20, null=True, verbose_name='快捷分诊')),
                ('insurance_type', models.CharField(blank=True, choices=[('SELF_PAY', '自费'), ('PUBLIC', '公费'), ('MEDICAL_INSURANCE', '医保'), ('COMMERCIAL', '商保'), ('HOSPITAL_STAFF', '本院职工'), ('STAFF_FAMILY', '职工家属'), ('OTHER_LOCATION', '异地医保'), ('NEW_RURAL', '新农合'), ('URBAN_RURAL', '城乡医保'), ('FIVE_GUARANTEES', '五保特困'), ('LOW_INSURANCE', '低保'), ('MILITARY', '军烈'), ('EARTHQUAKE', '512地震'), ('RAILWAY_STAFF', '轻轨工伤'), ('RAILWAY_INSURANCE', '铁路医保'), ('ROAD_FUND', '道路基金'), ('DISABILITY', '复员伤残'), ('DISABLED', '残疾'), ('ISOLATION', '担保'), ('HOMELESS', '无主病人'), ('HIGH_VALUE', '高价'), ('WORK_INJURY', '工伤'), ('TRAFFIC_INJURY', '车伤'), ('MATERNITY', '生育'), ('SPECIAL_AGREEMENT', '特约')], max_length=50, null=True, verbose_name='费别')),
                ('pain_score', models.IntegerField(blank=True, null=True, verbose_name='疼痛评分')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温')),
                ('injury_position', models.CharField(blank=True, choices=[('LIMB_SKIN', '四肢/皮肤'), ('BACK', '北部'), ('CHEST', '胸部'), ('ABDOMEN', '腹部'), ('HEAD_NECK', '头颈部')], max_length=50, null=True, verbose_name='小人图/损伤部位')),
                ('injury_type', models.CharField(blank=True, choices=[('LACERATION', '裂伤/挫伤'), ('STAB', '刺伤'), ('BLUNT', '钝性伤'), ('GUNSHOT', '弹道伤')], max_length=50, null=True, verbose_name='损伤类型')),
                ('other_inquiry', models.CharField(blank=True, choices=[('ADMISSION_CERT', '开住院证'), ('PRESCRIPTION', '开药'), ('MEDICAL_CERT', '开单'), ('NUCLEIC_TEST', '核酸检测')], max_length=50, null=True, verbose_name='非急诊类')),
                ('patient_type', models.CharField(blank=True, choices=[('THREE_NOS', '三无人员'), ('LOW_INCOME', '低保户'), ('SPECIAL_CARE', '特困户'), ('POOR_CARD', '建卡贫困户'), ('FIVE_GUARANTEES', '五保户'), ('8023_TEAM', '8023部队'), ('ACTIVE_MILITARY', '现役军人'), ('RETIRED_MILITARY', '退伍军人'), ('MISSING_PERSON', '失独人员')], max_length=50, null=True, verbose_name='身份标识')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.hospital', verbose_name='医院')),
            ],
            options={
                'verbose_name': '患者分诊提交',
                'verbose_name_plural': '患者分诊提交',
            },
        ),
    ]
