# Generated by Django 4.2.17 on 2025-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_alter_patienttriagesubmission_injury_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='injury_position',
            field=models.CharField(blank=True, choices=[('LIMB_SKIN', '四肢/皮肤'), ('BACK', '背部'), ('CHEST', '胸部'), ('ABDOMEN', '腹部'), ('HEAD_NECK', '头颈部'), ('BUTTOCKS', '臀部')], max_length=255, null=True, verbose_name='小人图/损伤部位'),
        ),
    ]
