# Generated by Django 4.2.17 on 2025-01-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_alter_patienttriagesubmission_injury_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='injury_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='小人图/损伤部位'),
        ),
    ]
