# Generated by Django 4.2.17 on 2025-01-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0004_alter_patienttriagesubmission_injury_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttriagesubmission',
            name='waitlist_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分诊排号'),
        ),
    ]
