# Generated by Django 4.2.17 on 2025-01-08 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_alter_vitalsigns_injury_position'),
        ('patient_portal', '0008_alter_patienttriagesubmission_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.hospital', verbose_name='医院'),
        ),
    ]
