# Generated by Django 4.2.17 on 2025-01-22 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_portal', '0010_alter_patientuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='医院'),
        ),
    ]
