# Generated by Django 4.2.17 on 2025-01-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0012_alter_patienttriagesubmission_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='other_inquiry',
            field=models.CharField(blank=True, choices=[('ADMISSION_CERT', '开住院证'), ('PRESCRIPTION', '开药'), ('MEDICAL_ORDER', '开单'), ('NUCLEIC_TEST', '核酸检测')], max_length=50, null=True, verbose_name='非急诊类'),
        ),
    ]
