# Generated by Django 4.2.17 on 2025-01-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0013_alter_patienttriagesubmission_other_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ID', '居民身份证'), ('HUKOU', '居民户口本'), ('HMT', '港澳台居民来往内地通行证'), ('PERMANENT', '外国人永久居留证'), ('PASSPORT', '护照'), ('MILITARY', '军官证')], max_length=20, null=True, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('SELF', '自费'), ('PUBLIC', '公费'), ('MEDICAL', '医保'), ('COMMERCIAL', '商保'), ('EMPLOYEE', '本院职工'), ('EMPLOYEE_FAMILY', '职工家属'), ('OTHER_REGION', '异地医保'), ('NEW_RURAL', '新农合'), ('URBAN_RURAL', '城乡医保'), ('FIVE_SPECIAL', '五保特困'), ('LOW_INCOME', '低保'), ('MILITARY', '军烈'), ('EARTHQUAKE_512', '512地震'), ('MINOR_INJURY', '轻轨工伤'), ('RAILWAY', '铁路医保'), ('ROAD_FUND', '道路基金'), ('DISABILITY', '复员伤残'), ('DISABLED', '残疾'), ('SPONSOR', '担保'), ('HOMELESS', '无主病人'), ('LEAVE', '离休'), ('WORK_INJURY', '工伤'), ('CAR_INJURY', '车伤'), ('MATERNITY', '生育'), ('SPECIAL', '特约')], max_length=50, null=True, verbose_name='费别'),
        ),
        migrations.AlterField(
            model_name='patienttriagesubmission',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('THREE_NO', '三无人员'), ('LOW_INCOME', '低保户'), ('SPECIAL_POVERTY', '特困户'), ('CARD_POVERTY', '建卡贫困户'), ('FIVE_GUARANTEE', '五保户'), ('MILITARY_8023', '8023部队'), ('ACTIVE_MILITARY', '现役军人'), ('RETIRED_MILITARY', '退伍军人'), ('ORPHANED', '失独人员')], max_length=50, null=True, verbose_name='身份标识'),
        ),
    ]
