# Generated by Django 4.2.17 on 2025-02-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0015_alter_patienttriagesubmission_injury_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='patient_portal.patientuser')),
            ],
        ),
    ]
