# Generated by Django 4.2.17 on 2025-02-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0016_patienttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
