# Generated by Django 4.2.17 on 2025-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0019_patienttriagesubmission_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttriagesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
