# Generated by Django 4.2.17 on 2025-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0020_patienttriagesubmission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='last_name',
        ),
    ]
