# Generated by Django 4.2.17 on 2025-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0021_remove_patientuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='id_medical_insurance',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='医保卡号'),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ID', '居民身份证'), ('HUKOU', '居民户口本'), ('HMT', '港澳台居民来往内地通行证'), ('PERMANENT', '外国人永久居留证'), ('PASSPORT', '护照'), ('MILITARY', '军官证')], default='ID', max_length=10, null=True, verbose_name='证件类型'),
        ),
    ]
