# Generated by Django 4.2.17 on 2025-02-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0022_patientuser_gender_patientuser_id_medical_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed_step', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority_response', models.CharField(blank=True, choices=[('UNDERSTOOD', '我理解了，下一条！'), ('USEFUL', '这个信息对我很有用～')], max_length=50, null=True)),
                ('symptom_response', models.CharField(blank=True, choices=[('USEFUL', '这个信息对我很有用～'), ('RELEVANT', '这个信息对我不是很有针对性')], max_length=50, null=True)),
                ('medication_response', models.CharField(blank=True, choices=[('KNOWN', '我已经知道这些信息啦'), ('USEFUL', '这个信息对我很有用～')], max_length=50, null=True)),
                ('heart_level', models.CharField(blank=True, choices=[('CALM', '平静的小溪流水'), ('URGENT', '急促的鼓点'), ('RELAXED', '轻快的散步节奏')], max_length=50, null=True)),
                ('energy_level', models.CharField(blank=True, choices=[('FULL', '刚充满电的手机'), ('COFFEE', '需要来杯咖啡'), ('LOW', '快没电的闹钟')], max_length=50, null=True)),
                ('waiting_feel', models.CharField(blank=True, choices=[('SUNSHINE', '阳光明媚'), ('CLOUD', '多云'), ('TEMPEST', '暴风雨')], max_length=50, null=True)),
                ('complete_step1', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_step2', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_step3', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('UNPAID', '未支付'), ('PAID', '已支付')], max_length=50, null=True)),
                ('terminal_trace', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.patientuser')),
            ],
            options={
                'verbose_name': '付费 ER Companion',
                'verbose_name_plural': '付费 ER Companion',
                'db_table': 'er_companion',
            },
        ),
    ]
