# Generated by Django 4.2.17 on 2025-02-12 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0036_remove_bookingonline_qr_code_and_more'),
        ('patient_portal', '0023_ercompanion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, choices=[(4000, '40元'), (5000, '50元'), (6000, '60元'), (7000, '70元')], default=5000, null=True, verbose_name='支付金额(分)')),
                ('status', models.CharField(blank=True, choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('REFUNDED', '已退款'), ('FAILED', '支付失败')], default='PENDING', max_length=20, null=True, verbose_name='支付状态')),
                ('terminal_trace', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='收钱吧流水号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('booking_online', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='followup.bookingonline', verbose_name='在线预约')),
            ],
            options={
                'verbose_name': '预约支付',
                'verbose_name_plural': '预约支付',
            },
        ),
    ]
