# Generated by Django 4.2.17 on 2025-02-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0024_bookingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.patientuser'),
        ),
    ]
