# Generated by Django 4.2.17 on 2025-02-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0026_patientuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('request_type', models.CharField(blank=True, choices=[('REFUND', '退款'), ('APP', 'app功能'), ('HOSPITAL', '医院信息'), ('PERSONAL', '个人信息'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='问题类型')),
                ('request_content', models.TextField(blank=True, null=True, verbose_name='问题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='提交时间')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_portal.patientuser', verbose_name='患者用户')),
            ],
            options={
                'verbose_name': '患者提交feedback',
                'verbose_name_plural': '患者提交feedback',
            },
        ),
    ]
