# Generated by Django 4.2.17 on 2025-01-05 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0010_alter_vitalsigns_injury_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='问卷问题')),
                ('question_category', models.CharField(blank=True, choices=[('GENERAL', '一般情况'), ('SYMPTOMS', '症状'), ('MEDICATION', '用药'), ('RECOVERY', '恢复情况'), ('SPECIAL_DISEASE', '特殊疾病相关')], max_length=50, null=True, verbose_name='问题分类')),
                ('question_type', models.CharField(blank=True, choices=[('TEXT', '文本'), ('YES_NO', '是否'), ('SINGLE_CHOICE', '单选'), ('RATING', '评分')], max_length=50, null=True, verbose_name='问题格式')),
                ('choice_one', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项一')),
                ('choice_two', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项二')),
                ('choice_three', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项三')),
                ('choice_four', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项四')),
                ('choice_five', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项五')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '标准问题',
                'verbose_name_plural': '标准问题',
            },
        ),
        migrations.CreateModel(
            name='FollowupRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('message_reply', models.CharField(blank=True, choices=[('WEEKEND', '周末'), ('WEEKDAY', '周中白天'), ('WEEKNIGHT', '周中晚上'), ('ANYTIME', '任意时间'), ('NO_REPLY', '未回复')], max_length=20, null=True, verbose_name='回复时间偏好')),
                ('survey_status', models.CharField(blank=True, choices=[('NOT_SENT', '未发送'), ('SENT_INCOMPLETE', '已发送未完成'), ('COMPLETED', '已完成')], default='NOT_SENT', max_length=20, null=True, verbose_name='问卷状态')),
                ('call_status', models.CharField(blank=True, choices=[('CALLED', '已电话随访'), ('NOT_CALLED', '未电话随访')], default='NOT_CALLED', max_length=20, null=True, verbose_name='电话随访状态')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='随访医院')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.patient', verbose_name='随访病人')),
                ('triage_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triagerecord', verbose_name='随访患者分诊记录')),
            ],
        ),
    ]
