# Generated by Django 4.2.17 on 2025-01-05 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0002_surveytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='填写时间')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='医院')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='followup.followuprecipient', verbose_name='问卷填写人')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='followup.surveytemplate', verbose_name='问卷模版')),
            ],
            options={
                'verbose_name': '随访问卷',
                'verbose_name_plural': '随访问卷',
            },
        ),
    ]
