# Generated by Django 4.2.17 on 2025-01-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0003_followupsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('answer_1', models.TextField(blank=True, null=True, verbose_name='答案一')),
                ('answer_2', models.TextField(blank=True, null=True, verbose_name='答案二')),
                ('answer_3', models.TextField(blank=True, null=True, verbose_name='答案三')),
                ('answer_4', models.TextField(blank=True, null=True, verbose_name='答案四')),
                ('answer_5', models.TextField(blank=True, null=True, verbose_name='答案五')),
                ('answer_6', models.TextField(blank=True, null=True, verbose_name='答案六')),
                ('answer_7', models.TextField(blank=True, null=True, verbose_name='答案七')),
                ('answer_8', models.TextField(blank=True, null=True, verbose_name='答案八')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='医院')),
                ('survey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='followup.followupsurvey', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '问卷回答',
                'verbose_name_plural': '问卷回答',
            },
        ),
    ]
