# Generated by Django 4.2.17 on 2025-01-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_alter_vitalsigns_injury_position'),
        ('followup', '0004_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecipient',
            name='triage_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='triage.triagerecord', verbose_name='随访患者分诊记录'),
        ),
    ]
