# Generated by Django 4.2.17 on 2025-01-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_alter_followuprecipient_triage_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuprecipient',
            name='uuid',
        ),
    ]
