# Generated by Django 4.2.17 on 2025-01-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0006_remove_followuprecipient_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupsurvey',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='uuid',
        ),
    ]
