# Generated by Django 4.2.17 on 2025-01-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0007_remove_followupsurvey_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='uuid',
        ),
    ]
