# Generated by Django 4.2.17 on 2025-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0008_remove_surveytemplate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模版创建人'),
        ),
    ]
