# Generated by Django 4.2.17 on 2025-01-08 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0009_alter_surveytemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsurvey',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='followupsurvey',
            name='status',
            field=models.CharField(blank=True, choices=[('INCOMPLETE', '未完成'), ('COMPLETE', '已完成')], default='INCOMPLETE', max_length=20, null=True, verbose_name='完成状态'),
        ),
    ]
