# Generated by Django 4.2.17 on 2025-01-08 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0010_followupsurvey_created_at_followupsurvey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='followupsurvey',
            name='status',
            field=models.CharField(blank=True, choices=[('NO_SEND', '未发送'), ('NO_RESPONSE', '已发送未完成'), ('YES_RESPONSE', '已完成')], default='NO_SEND', max_length=20, null=True, verbose_name='完成状态'),
        ),
    ]
