# Generated by Django 4.2.17 on 2025-01-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0011_surveytemplate_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='followuprecipient',
            name='call_status',
            field=models.CharField(blank=True, choices=[('YES_CALL', '已电话随访 (YES_CALL)'), ('NO_CALL', '未电话随访 (NO_CALL)')], default='NOT_CALLED', max_length=20, null=True, verbose_name='电话随访状态'),
        ),
        migrations.AlterField(
            model_name='followuprecipient',
            name='message_reply',
            field=models.CharField(blank=True, choices=[('WEEKEND', '周末 (WEEKEND)'), ('WEEK_DAY', '周中白天 (WEEK_DAY)'), ('WEEK_NIGHT', '周中晚上 (WEEK_NIGHT)'), ('ANYTIME', '任意时间 (ANYTIME)'), ('NOT_YET', '未回复 (NOT_YET)')], max_length=20, null=True, verbose_name='回复时间偏好'),
        ),
        migrations.AlterField(
            model_name='followuprecipient',
            name='survey_status',
            field=models.CharField(blank=True, choices=[('NO_SEND', '未发送 (NO_SEND)'), ('NO_RESPONSE', '已发送未完成 (NO_RESPONSE)'), ('YES_RESPONSE', '已完成 (YES_RESPONSE)')], default='NOT_SENT', max_length=20, null=True, verbose_name='问卷状态'),
        ),
    ]
