# Generated by Django 4.2.17 on 2025-01-09 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0013_followuprecipient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='followuprecipient',
            name='research_patient',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否为研究对象'),
        ),
    ]
