# Generated by Django 4.2.17 on 2025-01-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0014_surveytemplate_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='submitted_at',
        ),
    ]
