# Generated by Django 4.2.17 on 2025-01-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0015_remove_surveytemplate_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecipient',
            name='research_patient',
            field=models.BooleanField(blank=True, null=True, verbose_name='重点随访对象'),
        ),
    ]
