# Generated by Django 4.2.17 on 2025-01-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0016_alter_followuprecipient_research_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupsurvey',
            name='status',
        ),
    ]
