# Generated by Django 4.2.17 on 2025-01-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0017_remove_followupsurvey_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupNotetaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_notes', models.TextField(blank=True, null=True, verbose_name='随访原始记录')),
                ('processed_notes', models.TextField(blank=True, null=True, verbose_name='随访处理后记录')),
                ('created_by', models.TextField(blank=True, null=True, verbose_name='随访医护')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='随访时间')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='随访医院')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followup.followuprecipient', verbose_name='被随访人')),
            ],
            options={
                'verbose_name': '随访记录',
                'verbose_name_plural': '随访记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
