# Generated by Django 4.2.17 on 2025-01-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0018_followupnotetaking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followupnotetaking',
            options={'ordering': ['-created_at'], 'verbose_name': '电话随访AI记录', 'verbose_name_plural': '电话随访AI记录'},
        ),
        migrations.RemoveField(
            model_name='followuprecipient',
            name='phone',
        ),
    ]
