# Generated by Django 4.2.17 on 2025-01-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0012_alter_patient_patient_user'),
        ('followup', '0019_alter_followupnotetaking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupnotetaking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.patient', verbose_name='患者'),
        ),
    ]
