# Generated by Django 4.2.17 on 2025-01-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0010_alter_patientuser_id'),
        ('followup', '0020_followupnotetaking_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuprecipient',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.patientuser', verbose_name='患者账号'),
        ),
    ]
