# Generated by Django 4.2.17 on 2025-01-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0021_followuprecipient_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecipient',
            name='research_patient',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='重点随访对象'),
        ),
    ]
