# Generated by Django 4.2.17 on 2025-01-15 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0022_alter_followuprecipient_research_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='信息内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发送时间')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='医院')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followup.followuprecipient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '随访消息',
                'verbose_name_plural': '随访消息',
            },
        ),
    ]
