# Generated by Django 4.2.17 on 2025-01-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0023_followupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模版类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='随访模版')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '随访消息模版',
                'verbose_name_plural': '随访消息模版',
            },
        ),
    ]
