# Generated by Django 4.2.17 on 2025-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0026_alter_followuprecipient_message_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
    ]
