# Generated by Django 4.2.17 on 2025-01-24 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_portal', '0011_alter_patienttriagesubmission_hospital'),
        ('triage', '0015_vitalsigns_revised_trauma'),
        ('followup', '0028_surveyai'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='最早时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='最晚时间')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('status', models.CharField(blank=True, choices=[('PATIENT_SUBMITTED', '患者已下单'), ('HOSPITAL_ACCEPTED', '医院已接受订单'), ('CONSULTATION_COMPLETED', '问诊已完成'), ('CANCELLED', '已取消')], default='PATIENT_SUBMITTED', max_length=50, null=True, verbose_name='订单状态')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='接单医院')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.patient', verbose_name='对应患者')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_portal.patientuser', verbose_name='下单患者')),
            ],
            options={
                'verbose_name': '预约付费线上问诊',
                'verbose_name_plural': '预约付费线上问诊',
            },
        ),
    ]
