# Generated by Django 4.2.17 on 2025-01-24 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0029_bookingonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingonline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
    ]
