# Generated by Django 4.2.17 on 2025-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0030_alter_bookingonline_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingonline',
            name='qr_code',
            field=models.CharField(blank=True, default='NO.0257426067', max_length=255, null=True, verbose_name='支付二维码编号'),
        ),
        migrations.AddField(
            model_name='bookingonline',
            name='terminal_trace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='终端流水号'),
        ),
    ]
