# Generated by Django 4.2.17 on 2025-01-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0025_alter_hospital_id'),
        ('followup', '0031_bookingonline_qr_code_bookingonline_terminal_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingonline',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.hospital', verbose_name='接单医院'),
        ),
        migrations.AlterField(
            model_name='followupmessage',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='followupnotetaking',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='随访医院'),
        ),
        migrations.AlterField(
            model_name='followuprecipient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='随访医院'),
        ),
        migrations.AlterField(
            model_name='followupsurvey',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='surveyai',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital', verbose_name='医院'),
        ),
    ]
