# Generated by Django 4.2.17 on 2025-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0033_bookingonline_actual_time_alter_bookingonline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingonline',
            name='complaint',
            field=models.TextField(blank=True, null=True, verbose_name='主诉'),
        ),
        migrations.AddField(
            model_name='bookingonline',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='bookingonline',
            name='old_patient',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否曾在本院急诊科就诊'),
        ),
    ]
