# Generated by Django 4.2.17 on 2025-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0034_bookingonline_complaint_bookingonline_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingonline',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='医院拒绝接诊的原因说明', null=True, verbose_name='拒接接诊原因'),
        ),
    ]
