# Generated by Django 4.2.17 on 2025-02-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0035_bookingonline_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingonline',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='bookingonline',
            name='terminal_trace',
        ),
    ]
