# Generated by Django 4.2.17 on 2025-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('success', models.BooleanField(blank=True, default=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'AI使用记录',
                'verbose_name_plural': 'AI使用记录',
            },
        ),
    ]
